version: '3'
services:
  application:
    container_name: amirs-service
    image: demo/application
    build: .
    env_file: docset.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: pgdb
    image: postgres:12.3-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456