spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456

flyway:
  url: jdbc:postgresql://localhost:5433/postgres
  username: postgres
  password: 123456
  enable: true
  locations:
    - 'classpath:db/migration'