spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${APPLICATION_DS_URL:jdbc:postgresql://localhost:5434/postgres}
    username: ${APPLICATION_DS_USERNAME:postgres}
    password: ${APPLICATION_DS_PASSWORD:123456}

  flyway:
    url: ${APPLICATION_DS_URL:jdbc:postgresql://localhost:5434/postgres}
    user: ${APPLICATION_DS_USERNAME:postgres}
    password: ${APPLICATION_DS_PASSWORD:123456}
    enabled: true
    locations:
      - 'classpath:db/migration'