spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 123456


flyway:
  url: jdbc:postgresql://localhost:5434/postgres
  user: postgres
  password: 123456
  enabled: true
  locations:
    - 'classpath:db/migration'